name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Laravel Translations UI Pro
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill in the details below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe it clearly.
      placeholder: A clear and concise description of the problem. e.g. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Any alternative approaches you've thought of...

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case for this feature. How would it benefit you and other users?
      placeholder: Explain how this feature would be used and its benefits...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: Any additional information, mockups, or examples...
