name: Feature Request
description: Suggest a new feature or enhancement for Laravel Translations UI Pro
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you need and why.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve, or what workflow would it improve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or behavior you'd like to see.
    validations:
      required: true

  - type: dropdown
    id: feature_area
    attributes:
      label: Feature Area
      description: Which part of Pro does this relate to?
      options:
        - AI Translation
        - Glossary
        - Quality Validation
        - Approval Workflow
        - Analytics
        - Hardcoded Detection
        - Revision History
        - Context Scanning
        - Activity Log
        - Comments
        - New Feature Area
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've thought of?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, screenshots, links to similar features in other tools, etc.
